2024-07-05 19:45:22,003 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for data files: {'db.db'} (connection.py:299)
2024-07-05 19:45:22,203 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:301)
2024-07-05 19:45:22,215 - MainThread - sqlmesh.core.config.connection - INFO - Using existing DuckDB adapter due to overlapping data file: db.db (connection.py:295)
2024-07-05 19:45:29,854 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema db.sqlmesh__sqlmesh_example (evaluator.py:273)
2024-07-05 19:45:29,855 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:1916)
2024-07-05 19:45:29,856 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_CATALOG() (base.py:1916)
2024-07-05 19:45:29,859 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT table_name AS name, table_schema AS schema, CASE table_type WHEN 'BASE TABLE' THEN 'table' WHEN 'VIEW' THEN 'view' WHEN 'LOCAL TEMPORARY' THEN 'table' END AS type FROM information_schema.tables WHERE (table_catalog = 'db' AND table_schema = 'sqlmesh__sqlmesh_example') AND table_name IN ('sqlmesh_example__seed_model__1248844913', 'sqlmesh_example__incremental_model__3269816977__temp', 'sqlmesh_example__landing_model__2034464410__temp', 'sqlmesh_example__seed_model__1248844913__temp', 'sqlmesh_example__landing_model__2034464410', 'sqlmesh_example__full_model__3031530868__temp', 'sqlmesh_example__full_model__3031530868', 'sqlmesh_example__incremental_model__3269816977') (base.py:1916)
2024-07-05 19:45:29,901 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'db.sqlmesh__sqlmesh_example' (evaluator.py:888)
2024-07-05 19:45:29,901 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "db"."sqlmesh__sqlmesh_example" (base.py:1916)
2024-07-05 19:45:29,904 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating table 'db.sqlmesh__sqlmesh_example.sqlmesh_example__landing_model__2034464410__temp' (evaluator.py:1177)
2024-07-05 19:45:29,905 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE TABLE IF NOT EXISTS "db"."sqlmesh__sqlmesh_example"."sqlmesh_example__landing_model__2034464410__temp" AS SELECT "id" AS "id", "item_id" AS "item_id", "event_date" AS "event_date" FROM "raw_data_source_table" AS "raw_data_source_table" WHERE FALSE LIMIT 0 (base.py:1916)
2024-07-05 19:45:29,914 - MainThread - sqlmesh.core.context - ERROR - Apply Failure: Traceback (most recent call last):
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 227, in sequential_apply_to_dag
    fn(node)
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 300, in <lambda>
    lambda s: self._create_snapshot(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 706, in _create_snapshot
    evaluation_strategy.create(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1200, in create
    self.adapter.ctas(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/shared.py", line 267, in internal_wrapper
    return func(*list_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 485, in ctas
    return self._create_table_from_source_queries(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 679, in _create_table_from_source_queries
    self._create_table(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 717, in _create_table
    self.execute(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 1913, in execute
    self._execute(sql, **kwargs)
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/engine_adapter/base.py", line 1919, in _execute
    self.cursor.execute(sql, **kwargs)
duckdb.duckdb.CatalogException: Catalog Error: Table with name raw_data_source_table does not exist!
Did you mean "duckdb_tables"?
LINE 1: ...id", "event_date" AS "event_date" FROM "raw_data_source_table" AS "raw_data_so...
                                                  ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 1207, in apply
    self._apply(plan, circuit_breaker)
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/context.py", line 1760, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(plan, circuit_breaker=circuit_breaker)
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/plan/evaluator.py", line 109, in evaluate
    self._push(plan, deployability_index_for_creation)
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/plan/evaluator.py", line 200, in _push
    self.snapshot_evaluator.create(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/core/snapshot/evaluator.py", line 298, in create
    concurrent_apply_to_snapshots(
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 198, in concurrent_apply_to_dag
    return sequential_apply_to_dag(dag, fn, raise_on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luketych/Dev/_Playground/sqlmesh-example/.venv/lib/python3.12/site-packages/sqlmesh/utils/concurrency.py", line 230, in sequential_apply_to_dag
    raise NodeExecutionFailedError(node) from ex
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"db"."sqlmesh_example"."landing_model": 3622554007>
 (context.py:1215)
2024-07-05 19:45:29,916 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
